# Generated by Django 5.0.6 on 2024-06-02 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showsession',
            name='astronomy_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.astronomyshow'),
        ),
        migrations.AddField(
            model_name='showsession',
            name='planetarium_dome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_sessions', to='api.planetariumdome'),
        ),
        migrations.AddField(
            model_name='astronomyshow',
            name='show_theme',
            field=models.ManyToManyField(related_name='astronomy_shows', to='api.showtheme'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='api.reservation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='show_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.showsession'),
        ),
    ]
