# Generated by Django 5.0.6 on 2024-06-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_showsession_astronomy_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomyshow',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
