# Generated by Django 5.0.6 on 2024-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_astronomyshow_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetariumdome',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
