# Generated by Django 5.0.6 on 2024-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_planetariumdome_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-reservation__created_at',)},
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('show_session', 'row', 'seat'), name='unique_ticket'),
        ),
    ]
